#!/bin/bash

# Verify the user has root privileges
if [ $EUID -ne 0 ]; then
    echo "This script must be run as root (or with sudo)."
    exit 1
fi

# Remove the symbolic link with AVL to /usr/local/bin/avl
rm /usr/local/bin/avl

# Remove the symbolic link with AVL uninstaller to /usr/local/bin/avl-uninstall
rm /usr/local/bin/avl-uninstall

# Remove the symbolic link with AVL updater to /usr/local/bin/avl-update
rm /usr/local/bin/avl-update